name: [yourapp]
directory:
  type: api
  settings:
    jsonrpc_client:
      tls:
        certificate_file: "$DIR/../../certs/[yourapp].crt"
        key_file: "$DIR/../../certs/[yourapp].key"
        ca_certificate_file: "$DIR/../../certs/root.crt"
    ca_certificate_file: "$DIR/../../certs/staging-root.crt"
    endpoints: [ "https://iris.staging.iris-gateway.de:3322/jsonrpc" ]
    server_names: [ "sd-1" ]
channels: # defines all the channels that we want to open when starting the server
  - name: Stdout channel
    type: stdout
    settings: {}
  - name: main gRPC server # accepts incoming gRPC connections to deliver and receive messages
    type: grpc_server
    settings:
      bind_address: "localhost:4445"
      tls:
        ca_certificate_file: "$DIR/../../certs/root.crt"
        certificate_file: "$DIR/../../certs/[yourapp].crt"
        key_file: "$DIR/../../certs/[yourapp].key"
  - name: main JSON-RPC server # accepts incoming JSONRPC connections to deliver and receive messages
    type: jsonrpc_server
    settings:
      bind_address: "localhost:5556"
      cors:
        allowed_hosts: ["^http(?:s)?://localhost\\:\\d+$"]
      tls:
        ca_certificate_file: "$DIR/../../certs/root.crt"
        certificate_file: "$DIR/../../certs/[yourapp].crt"
        key_file: "$DIR/../../certs/[yourapp].key"
  - name: main JSON-RPC client # creates outgoing JSONRPC connections to deliver and receive messages
    type: jsonrpc_client
    settings:
      endpoint: http://[your-host]:[your-port]/[your-endpoint]
